project:
  type: website

website:
  title: "Tomoya Ozawa"
  navbar:
    background: "#27285C"
    left:
      - href: index.qmd
        text: Home
      - href: blog_test.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

